spring:
  application:
    name: void-es
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://void-es:8761/eureka
    register-with-eureka: false
    fetch-registry: false
