services:

  void-es:
    image: void-es
    container_name: void-es
    networks:
      - void-network
    ports:
      - "8761:8761"
      
      
  void-db-progression:
    image: void-db
    networks:
      - void-network
    volumes:
      - ./void-db/progression:/var/lib/postgresql/data
    container_name: void-db-progression
    #restart: unless-stopped 
    
  void-db-creatures:
    image: void-db
    networks:
      - void-network
    volumes:
      - ./void-db/creatures:/var/lib/postgresql/data
    container_name: void-db-creatures
    #restart: unless-stopped 
      
  void-db-users:
    image: void-db
    networks:
      - void-network
    volumes:
      - ./void-db/users:/var/lib/postgresql/data
    container_name: void-db-users
    #restart: unless-stopped 
    
    
  void-progression:
    image: void-progression
    networks:
      - void-network
    depends_on: 
      - void-es
      - void-db-progression
    container_name: void-progression
    #restart: unless-stopped 
    
  void-creatures:
    image: void-creatures
    networks:
      - void-network
    depends_on: 
      - void-es
      - void-db-creatures
    container_name: void-creatures
    #restart: unless-stopped    
           
  void-gateway:
    image: void-gateway
    ports:
      - "8090:8080"
    networks:
      - void-network
    depends_on: 
      - void-es
    container_name: void-gateway
    #restart: unless-stopped 
    
  void-security:
    image: void-security
    networks:
      - void-network
    depends_on: 
      - void-es
    container_name: void-security
    #restart: unless-stopped 
    
  void-controller:
    image: void-controller
    networks:
      - void-network
    depends_on: 
      - void-es
    container_name: void-controller
    #restart: unless-stopped 
      
networks:
  void-network:
    driver: bridge
    name: void-network
    
    
