services:

  void-es:
    image: void-es
    container_name: void-es
    networks:
      - void-network
    ports:
      - "8761:8761"
      
  void-db-users:
    image: void-db
    networks:
      - void-network
    volumes:
      - ./void-db/users:/var/lib/postgresql/data
    container_name: void-db-users
    restart: unless-stopped 
           
  void-gateway:
    image: void-gateway
    ports:
      - "8090:8080"
    networks:
      - void-network
    depends_on: 
      - void-es
    container_name: void-gateway
    restart: unless-stopped 
    
  void-security:
    image: void-security
    networks:
      - void-network
    depends_on: 
      - void-es
    container_name: void-security
    restart: unless-stopped 
      
networks:
  void-network:
    driver: bridge
    name: void-network
    
    
